# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Spider\ErrorPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 480)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 720, 480))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.Error_Str = SubtitleLabel(self.widget)
        self.Error_Str.setGeometry(QtCore.QRect(-1, 380, 720, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Error_Str.setFont(font)
        self.Error_Str.setAlignment(QtCore.Qt.AlignCenter)
        self.Error_Str.setObjectName("Error_Str")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(260, 140, 200, 200))
        self.widget_2.setObjectName("widget_2")
        self.ProgressRing = ProgressRing(self.widget_2)
        self.ProgressRing.setGeometry(QtCore.QRect(0, 0, 200, 200))
        self.ProgressRing.setMinimumSize(QtCore.QSize(200, 200))
        self.ProgressRing.setMaximumSize(QtCore.QSize(200, 200))
        self.ProgressRing.setProperty("value", 100)
        self.ProgressRing.setStrokeWidth(10)
        self.ProgressRing.setObjectName("ProgressRing")
        self.BackButton = PrimaryPushButton(self.widget_2)
        self.BackButton.setGeometry(QtCore.QRect(70, 80, 60, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Error_Str.setText(_translate("Form", "Error Code"))
        self.BackButton.setText(_translate("Form", "返回"))
from qfluentwidgets import PrimaryPushButton, ProgressRing, SubtitleLabel
