# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Xylit\Desktop\Spider\LoadingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 480)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 720, 480))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.rounding = IndeterminateProgressRing(self.widget)
        self.rounding.setGeometry(QtCore.QRect(260, 140, 200, 200))
        self.rounding.setMinimumSize(QtCore.QSize(200, 200))
        self.rounding.setMaximumSize(QtCore.QSize(200, 200))
        self.rounding.setStrokeWidth(10)
        self.rounding.setObjectName("rounding")
        self.Title = SubtitleLabel(self.widget)
        self.Title.setGeometry(QtCore.QRect(0, 380, 720, 27))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.processingpage = QtWidgets.QWidget(self.widget)
        self.processingpage.setGeometry(QtCore.QRect(260, 140, 200, 200))
        self.processingpage.setObjectName("processingpage")
        self.processing = ProgressRing(self.processingpage)
        self.processing.setGeometry(QtCore.QRect(0, 0, 200, 200))
        self.processing.setMinimumSize(QtCore.QSize(200, 200))
        self.processing.setMaximumSize(QtCore.QSize(200, 200))
        self.processing.setStrokeWidth(10)
        self.processing.setObjectName("processing")
        self.Title.raise_()
        self.rounding.raise_()
        self.processingpage.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title.setText(_translate("Form", "解析中"))
from qfluentwidgets import IndeterminateProgressRing, ProgressRing, SubtitleLabel
